### ISSUE TITLE
Error initializing after compile ubuntu 22

### ISSUE THREAD

**Issue by leo36dff** [Black-Tek/BlackTek-Server#26] opened 2024-11-21 19:04 UTC
After following the entire tutorial i tried to compile on ubuntu 22

![image](https://github.com/user-attachments/assets/1bb900d6-1039-4fab-88c8-dee01e528973)
it compiles with no error, but when i try to give ./ot(whatever) it shows core dumped...

**Comment by Codinablack** [comment] 2024-11-21 20:39
Which tutorial, the one on the wiki? 

That thing was just a copy and paste job of gesior's instructions on how to compile it. It was put there as a temporary guide.

I don't know why it would immediately core dump unless you ended up grabbing mismatched libs (for a different architecture or platform).

There is also no instructions anywhere that says to run it you type

```./ot```

not sure where you got that from... if you simply renamed the outputted executable, then yeah that would make sense, but the screenshot you show, it doesn't not show anything like that, looks like you just compiled and immediately typed in some unknown command.

My suggestion, if it's not a simple mismatched lib or name, then I would try to revert everything and go back to a clean state that you were in before doing anything, and use the bootstrap.sh to install and setup the server. It's what it was made for!

I guess many don't know about it yet, but the bootstrap.sh is the way to go, it was created with the intention of simplifying the process to getting started on ANY linux machine out there, and has been tested across MANY different OS's and on both x64 and ARM64 architectures...


The above reminded me... we don't support 32 bit builds, so if you tried to do the entire process using 32 bit libs and stuff instead, then that could also be a reason you are running into this problem

**Comment by leo36dff** [comment] 2024-11-21 20:43
Thx for reply Cod, yea, i renames it to ot lol. I use this github Wiki page using vcpkg and premake, didnt know it wereca copypaste of tfs or whatever, i will try again and post the news. Ty. Using ubuntu 22 x64

**Comment by leo36dff** [comment] 2024-11-21 21:06
![image](https://github.com/user-attachments/assets/3cd67396-13ef-42e0-bda3-6cb78357e96a)
Fresh start, updated ubuntu 22, everything installed like vcpkg, bootstrap etc. Using now bootstrap.sh It says everything ok but afeter... core dumped... You any any specific information or print? All that i know and can say to you what i did ive already described it here.

**Comment by leo36dff** [comment] 2024-11-21 21:09
![image](https://github.com/user-attachments/assets/0bd82859-3e4e-42e3-aea4-35020cc67848)
BTw my vps config. ubuntu 22 fully upgraded

**Comment by Codinablack** [comment] 2024-11-21 21:51
If you could share the core dump that would be helpful in determining the problem.

What architecture is your OS running on?

**Comment by Codinablack** [comment] 2024-11-21 21:54
Yes I just did a quick search and that seems to be the common reason this happens:

![image](https://github.com/user-attachments/assets/f94475af-3a6b-41b2-a14e-b03211e313b5)

Seems to me you chose x64, and are running on ARM64 VPS most likely

**Comment by leo36dff** [comment] 2024-11-21 22:15
![image](https://github.com/user-attachments/assets/36130de6-a6b7-465a-aaf6-dfb4e458cc4b)
Im running a x64 xeon processor. Share my core dump? Idn what it means. No log created/found, im compiling right now on debug mode, i will post here soon.

**Comment by leo36dff** [comment] 2024-11-21 22:21
Updating:

1: step

![image](https://github.com/user-attachments/assets/364b38fc-9b79-48b4-971c-10cce6baa972)

2: step

![image](https://github.com/user-attachments/assets/2fb082b9-3ff6-4a2e-9aa6-f6c8e0ce5acb)

3: step

![image](https://github.com/user-attachments/assets/e5f8dd60-be63-4e88-98f7-ba0593b5508c)


All files generated sucessfuly on debug mode.

**Comment by Codinablack** [comment] 2024-11-22 02:46
The generation of the files is not a problem. The compiling is not a problem.

The problem is most certainly a mismatch on architecture somewhere, or lack of support for the AVX specified.

The core being dumped is supposed to be in the location /var/lib/apport/coredump or /var/crash
I'm not sure which is the correct location, it may be that your machine has a different location configured. You need to find that, and you also need to use GDB to analyze it to provide some valuable information about what led to the crash.

I am not a linux super user. Just searching that error results in all replies saying its a cpu architecture mismatch or a problem with the cpu not supporting the specified AVX. That's it. Nothing to do with this project in of itself, but rather with the configuration on your side. You could try adjusting or removing the specifications for AVX in premake, but I am doubtful that is the problem. Even though your terminal is showing you running a x86_64 type CPU, I still believe it's going to come down to an issue with the wrong architecture selected somewhere along the way. Either a lib, or all the libs, or entire project (most likely).

Changing between debug and release shouldn't matter at all, and if it does, then that is a for sure sign that there is a problem with the dependencies. 

Anyway it goes, I can't really resolve that problem for you; at best I can try to identify the problem with you if you provide more information, but ultimately I have already told you the possible issues, its going to be up to you to figure out where something went wrong.

I have had many users use that script without any problems getting set up. There is even a guy who has an entire kubernates cluster running on ARM64 based, free servers. The person who wrote the script actually tested out nearly 20 versions of linux, and on mulitple machines, even used the script to install black tek server on his phone... he is a linux super user for sure, but sadly I am not.

**Comment by Codinablack** [comment] 2024-11-22 02:51
The workflow I have produces a binary for ubuntu 22. If all else fails, you can just fork this repo on your github, edit the workflow to save the binary somewhere and run it, because its producing binaries without failure. I plan to eventually add to the workflow to store the produced binaries but right now I have a lot of other things that are calling priority, like the finishing of this system I have been building for months, and fixing all the bugs on this repo. 

It should be pretty straight forward, to push the binary somewhere, just lookup a tutorial or some example code on how to upload a binary or "nightly" sometimes they are referred to as... and then you can just download the binary.

**Comment by Codinablack** [comment] 2024-11-24 00:52
@leo36dff Have you had any luck resolving your problem?

**Comment by leo36dff** [comment] 2024-11-27 03:15
No Codinablack im sorry, i tried everything for 2 days with no lucky. I have only that vps to test. Maybe is something with my VPS idn (cause any other distros i can compile and execute). Btw thanks for your effort. Maybe i try some day later.

**Comment by Codinablack** [comment] 2024-11-28 02:54
I have a friend who is currently digging into this issue to see if we can find and resolve the problem for you and future users. He is quite experienced in using linux and so I am hopeful he should be able to isolate the problem. He has already started looking in a specific direction and I think he is probably correct, but the idea is that your CPU on your VPS is not compatible with older AVX, instead it only supports AVX2, which if I recall correctly, we aren't even supporting currently because I didn't realize that at this point AVX2 is already old. So its possible shifting to a minimum required AVX2 might be the way to go, or we might be able to support AVX and AVX2 with different configurations.. not sure what we are going to do, or if that is actually even your problem, but I just wanted to let you know, it is being looked into on our end and I would like for this to be resolved for you and all of BlackTek's users.

**Comment by Codinablack** [comment] 2024-12-06 21:49
This issue can't be replicated, most likely the CPU does not support AVX, possibly it supports only AVX2 or no AVX at all. Investigation into this compatibility issue is ongoing and in the future we may remove AVX in favor of AVX2, but for now, the server is just going to have to be ran on a CPU that supports AVX.

**Closed by Codinablack** 2024-12-06 21:49 UTC
