### ISSUE TITLE
Walking bug crossing monsters

### ISSUE THREAD

**Issue by leo36dff** [Black-Tek/BlackTek-Server#27] opened 2024-11-27 17:45 UTC
https://github.com/user-attachments/assets/03847c6c-30ce-45a1-a875-fa8327629065

https://github.com/user-attachments/assets/afbeadbe-aff2-4e69-b998-56ef347f3d6a

Should check this out.
BTK- Augments, fresh compile
OTCV8 otacademy fresh compile
10.98 official sprites

**Comment by Codinablack** [comment] 2024-11-27 22:05
Ok so with the first video, you are demonstrating that you can't step onto a monster??? Is that the purpose of the video? I thought stepping on a tile already occupied by a monster was not allowed... is this not supposed to be the case?

The second video, I have no idea what the problem is, all I see is you run up and down parcels over and over again, but I didn't catch what the problem was, could you please explain these problems to me?

**Comment by leo36dff** [comment] 2024-11-27 22:16
First video, check his feets. its glitching so much when you are at monsters side and try to move to his direction, try yourself and check it out for better understading. 

Second video you cannot climb more than 1 parcel at once, the player has to stop in front of 2 or more parcels, cant step over it

**Comment by Codinablack** [comment] 2024-11-27 22:21
The feet issue is with packets. Its because you are constantly sending movement packets, and the client wants to move you there, but you are not allowed to move there.. I'm not even positive that it could possibly be fixed on the server side... and I know if you continue to flood packets it will kick you... I am unsure there is anything more I could do about that, but I will try.

The second video, you say the player cannot climb more than one parcel at a time, but I clearly watch you climb a stack of four with one step, so I am again confused

**Comment by leo36dff** [comment] 2024-11-27 22:22
Both issues has fixes on foruns, i have seen exactly the same problems with others distros... i think i can fix it and send a pr if you wish,.

**Comment by Codinablack** [comment] 2024-11-27 22:29
@leo36dff 

I have confirmed with others and with tibia wiki.

Players are not supposed to walk through monsters, but GM's should be able to do so when in Ghost mode.
Players can walk through each other when not in depot, but are in pz, and the config option, is set:
```allowWalkthrough = true```

The last thing, about parcels. You are mistaken. Tibia stopped blocking going up multiple parcels at a time during 7.5 update, and its been like that every since.

https://tibia.fandom.com/wiki/Updates/7.5

As for the GM's being able to walk through creatures, I can fix that sometime, should be relatively easy, but as for the problem with the feet "glitching" if you have a PR or thread on otland you know that fixes this, then by all means, point me in the right direction.

**Comment by Codinablack** [comment] 2024-11-27 22:36
Or yeah if you can put in PR that fixes the problem with the feet that would be nice, but as far as I can tell, you are supposed to be able to step up onto those parcels.. that is how I remember tibia and I just played a couple years ago, that is how everyone in OTA discord says it is supposed to be, and that is also what tibia wiki says as well, so I will prefer to just leave it like that, rather than mix in old mechanics with newer ones.

**Comment by leo36dff** [comment] 2024-11-28 01:15
Ok Ok, i will post soon, btw cod, is there a way to use the native otc/v8 imbuement module instead modalwindow?

**Comment by leo36dff** [comment] 2024-11-28 01:31
https://github.com/user-attachments/assets/22507d28-4bda-4a37-a850-95dafbc850d0

its not about packets, nor allow walthrough or whatever, but i will fix it.

**Comment by Codinablack** [comment] 2024-11-28 02:46
> Video.do.WhatsApp.de.2024-11-27.a.s.22.30.44_f33d459a.mp4
> 
> its not about packets, nor allow walthrough or whatever, but i will fix it.

Yeah silba did some more thorough testing and found where the feet glitch issue occurs in multiple situations and has mapped out all the situations when this happens and it shouldn't for me. 

![image](https://github.com/user-attachments/assets/86edd144-0734-4911-bdb3-da32632328e8)
If you already know where exactly to make the changes to fix these issues that is fantastic.

The parcel thing tho, that is just and old school tibia mechanic. 

As for your question about making the imbuements work with OTCv8's imbuements module. I am sure its quite possible to do, as all I did was build an API, the "tibia imbuements" were built on top of that API in lua by Ohman. You can completely remove it and rewrite it your own way and so that it accepts extendedOpCodes from OTCv8 if you wish. I don't personally use or advocate the use of OTCv8, so I really don't know how much work it would be to modify on either side, but I'm certain it is for sure doable.

**Comment by Codinablack** [comment] 2024-12-06 21:43
d950f2aaaedf4f35456608265dbb98c16c334637 Resolves this issue.

**Closed by Codinablack** 2024-12-06 21:43 UTC
